name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ["chat", "pets", "todo", "inspector"]
        # example: ["twit", "chat", "counter-js-auth0", "pets", "twit", "file-drop", "inspector"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: gardencmp
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pnpm Build
      run: |
        pnpm install
        pnpm turbo build;
      working-directory: ./examples/${{ matrix.example }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: ./examples/${{ matrix.example }}
        push: true
        tags: ghcr.io/gardencmp/${{github.event.repository.name}}-example-${{ matrix.example }}:${{github.head_ref || github.ref_name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}}
        cache-from: type=gha
        cache-to: type=gha,mode=max