name: End-to-End Tests for React Native

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

jobs:
  e2e-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        rnapp: [
          "chat-rn",
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: pnpm turbo build --filter="./packages/*"

      - name: iOS Simulator
        uses: futureware-tech/simulator-action@v4
        with:
          os: iOS
          wait_for_boot: true

      # - name: Install Maestro
      #   run: |
      #     curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: ${{ matrix.rnapp }} App Build
        working-directory: ./examples/${{ matrix.rnapp }}
        run: |
          pnpm install
          pnpm build
          pnpm ios &

      - name: ${{ matrix.rnapp }} App Test
        working-directory: ./examples/${{ matrix.rnapp }}
        run: |
          maestro test test/e2e/flow.yml
