name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Source
        uses: ./.github/actions/source.yml

      - name: Install Playwright Browsers
        run: pnpm exec playwright install

      - name: Unit Tests
        run: pnpm test:ci
